/* tslint:disable */
/* eslint-disable */
/**
 * Celebrity Map
 * 유명인 맛지도 백오피스/앱 API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AuthLoginDto, ProfileEntity } from '../models';
import {
  AuthLoginDtoFromJSON,
  AuthLoginDtoToJSON,
  ProfileEntityFromJSON,
  ProfileEntityToJSON,
} from '../models';

export interface PostLoginRequest {
  authLoginDto: AuthLoginDto;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   *
   */
  async getProfileRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProfileEntity>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/auth/profile`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProfileEntityFromJSON(jsonValue)
    );
  }

  /**
   *
   */
  async getProfile(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ProfileEntity> {
    const response = await this.getProfileRaw(initOverrides);
    return await response.value();
  }

  /**
   *
   */
  async postLoginRaw(
    requestParameters: PostLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (
      requestParameters.authLoginDto === null ||
      requestParameters.authLoginDto === undefined
    ) {
      throw new runtime.RequiredError(
        'authLoginDto',
        'Required parameter requestParameters.authLoginDto was null or undefined when calling postLogin.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/auth/login`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AuthLoginDtoToJSON(requestParameters.authLoginDto),
      },
      initOverrides
    );

    return new runtime.TextApiResponse(response) as any;
  }

  /**
   *
   */
  async postLogin(
    requestParameters: PostLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.postLoginRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
