/* tslint:disable */
/* eslint-disable */
/**
 * Celebrity Map
 * 유명인 맛지도 백오피스/앱 API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginDto
 */
export interface AuthLoginDto {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginDto
     */
    password: string;
}

/**
 * Check if a given object implements the AuthLoginDto interface.
 */
export function instanceOfAuthLoginDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthLoginDtoFromJSON(json: any): AuthLoginDto {
    return AuthLoginDtoFromJSONTyped(json, false);
}

export function AuthLoginDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function AuthLoginDtoToJSON(value?: AuthLoginDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

