/* tslint:disable */
/* eslint-disable */
/**
 * Celebrity Map
 * 유명인 맛지도 백오피스/앱 API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalMapLinkEntity
 */
export interface ExternalMapLinkEntity {
    /**
     * 
     * @type {number}
     * @memberof ExternalMapLinkEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ExternalMapLinkEntity
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalMapLinkEntity
     */
    value: string;
}

/**
 * Check if a given object implements the ExternalMapLinkEntity interface.
 */
export function instanceOfExternalMapLinkEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ExternalMapLinkEntityFromJSON(json: any): ExternalMapLinkEntity {
    return ExternalMapLinkEntityFromJSONTyped(json, false);
}

export function ExternalMapLinkEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalMapLinkEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'value': json['value'],
    };
}

export function ExternalMapLinkEntityToJSON(value?: ExternalMapLinkEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'value': value.value,
    };
}

