/* tslint:disable */
/* eslint-disable */
/**
 * Celebrity Map
 * 유명인 맛지도 백오피스/앱 API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RestaurantEntity } from './RestaurantEntity';
import {
    RestaurantEntityFromJSON,
    RestaurantEntityFromJSONTyped,
    RestaurantEntityToJSON,
} from './RestaurantEntity';

/**
 * 
 * @export
 * @interface GetRestaurantsResponse
 */
export interface GetRestaurantsResponse {
    /**
     * 
     * @type {Array<RestaurantEntity>}
     * @memberof GetRestaurantsResponse
     */
    restaurants: Array<RestaurantEntity>;
    /**
     * 
     * @type {number}
     * @memberof GetRestaurantsResponse
     */
    count: number;
}

/**
 * Check if a given object implements the GetRestaurantsResponse interface.
 */
export function instanceOfGetRestaurantsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "restaurants" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function GetRestaurantsResponseFromJSON(json: any): GetRestaurantsResponse {
    return GetRestaurantsResponseFromJSONTyped(json, false);
}

export function GetRestaurantsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRestaurantsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'restaurants': ((json['restaurants'] as Array<any>).map(RestaurantEntityFromJSON)),
        'count': json['count'],
    };
}

export function GetRestaurantsResponseToJSON(value?: GetRestaurantsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'restaurants': ((value.restaurants as Array<any>).map(RestaurantEntityToJSON)),
        'count': value.count,
    };
}

