/* tslint:disable */
/* eslint-disable */
/**
 * Celebrity Map
 * 유명인 맛지도 백오피스/앱 API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileEntity
 */
export interface ProfileEntity {
    /**
     * 
     * @type {number}
     * @memberof ProfileEntity
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileEntity
     */
    username: string;
}

/**
 * Check if a given object implements the ProfileEntity interface.
 */
export function instanceOfProfileEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function ProfileEntityFromJSON(json: any): ProfileEntity {
    return ProfileEntityFromJSONTyped(json, false);
}

export function ProfileEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'username': json['username'],
    };
}

export function ProfileEntityToJSON(value?: ProfileEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'username': value.username,
    };
}

