/* tslint:disable */
/* eslint-disable */
/**
 * Celebrity Map
 * 유명인 맛지도 백오피스/앱 API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCelebrityDto
 */
export interface UpdateCelebrityDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCelebrityDto
     */
    celebrityName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCelebrityDto
     */
    celebrityPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCelebrityDto
     */
    channelName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCelebrityDto
     */
    profileImage?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCelebrityDto
     */
    markerOnImage?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCelebrityDto
     */
    markerOffImage?: string;
}

/**
 * Check if a given object implements the UpdateCelebrityDto interface.
 */
export function instanceOfUpdateCelebrityDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateCelebrityDtoFromJSON(json: any): UpdateCelebrityDto {
    return UpdateCelebrityDtoFromJSONTyped(json, false);
}

export function UpdateCelebrityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCelebrityDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'celebrityName': !exists(json, 'celebrityName') ? undefined : json['celebrityName'],
        'celebrityPhone': !exists(json, 'celebrityPhone') ? undefined : json['celebrityPhone'],
        'channelName': !exists(json, 'channelName') ? undefined : json['channelName'],
        'profileImage': !exists(json, 'profileImage') ? undefined : json['profileImage'],
        'markerOnImage': !exists(json, 'markerOnImage') ? undefined : json['markerOnImage'],
        'markerOffImage': !exists(json, 'markerOffImage') ? undefined : json['markerOffImage'],
    };
}

export function UpdateCelebrityDtoToJSON(value?: UpdateCelebrityDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'celebrityName': value.celebrityName,
        'celebrityPhone': value.celebrityPhone,
        'channelName': value.channelName,
        'profileImage': value.profileImage,
        'markerOnImage': value.markerOnImage,
        'markerOffImage': value.markerOffImage,
    };
}

